### ISSUE TITLE
Create clustering algorithm to group PGPIDs

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/geniza#105]
Extract keywords from the description, parse through tags, and use language data and document type to inform a clustering algorithm.

**Useful Links**
* [Gissoo's tag network](https://app.asana.com/0/1180442654095587/1200050965936158/f)

**Potential uses:**
* Gissoo's search engine
* "Other similar documents" in detail view?

**Potential roadblocks:**
* Metadata isn't entirely clean yet, so preliminary results may not be as informative.
* What value of K should be used if we use KMeans? 

**Road map**
- [ ] Find limits / plan out matrix structure
    - [x] Determine unique tags, get count, and make plan for how to handle tags in cluster
    - [x] Experiment with keyword libraries to collect data from descriptions
    - [ ] Copy languagescript and doc type import scripts and create clean data
    - [ ] Find overlap between languages, tags, and keywords and propose dimensionality reduction if possible.
    - [ ] Assess how many PGPIDs (if any) are lost from cluster analysis when reduction occurs.
- [ ] Apply pre-processing and turn into one-hot vectors:
    - [ ] Tags
    - [ ] Description
    - [ ] LanguageScripts & doc type
- [ ] Train clustering model
    - [ ] How much time does it take to train the model?
    - [ ] Tweak as necessary: What value of K gives coherent results?

**Experiment notes**
* The tags follow a "long tail" distribution. [Here is a link to the tag counts](https://docs.google.com/spreadsheets/d/1bLPJde1grZ4007nn81EB89LkghRzZSW3QqNUIOe80HA/edit#gid=0). For efficiency purposes, we may want to cut off tags with fewer than... 10 PGPIDs that share that document? I'll start with 2 and work my way up.
     * There are 2133 unique tags.
     * Many tags duplicate language, library, or description data. Those can be collapsed / removed.
* To determine keywords from the description, the application of [rake-nltk](https://pypi.org/project/rake-nltk/) was mildly successful, though it's punctuation stripping left some hyphenated names split into two keywords. It was fast, however, and easy to implement. For an MVP, it'll be sufficient. It detected 74k unique keywords. After stripping out keywords with count less than 1, there were 17k unique keywords, setting the filter to 5, there were 5100 keywords.

### Code
**Tag pre-processing analysis**
```python
import pandas as pd

metadata = '%$%^'
df = pd.read_csv(metadata)

tag_lists = [[tag.strip() for tag in tag_list.split('#') if tag.strip()] for tag_list in df['Tags'].dropna().tolist() if tag_list != '']
all_tags = [tag.lower() for tag_list in tag_lists for tag in tag_list]

d = {}
for tag in all_tags:
    d[tag] = d.get(tag, 0) + 1

df_t = pd.DataFrame()
df_t['tag'] = d.keys()
df_t['count'] = df_t['tag'].apply(lambda x: d[x])
df_t.sort_values('count', ascending=False).to_csv('tag_count.csv', index=False)
```

**Description pre-processing analysis**
```python
from rake_nltk  import Rake

descriptions = df['Description'].dropna().unique().tolist()

keyword_d = {}

for desc in descriptions:
    rake = Rake()
    rake.extract_keywords_from_text(desc)
    keyword_l = rake.get_ranked_phrases()
    for keyword in keyword_l:
        keyword_d[keyword] = keyword_d.get(keyword, 0) + 1

df_t = pd.DataFrame()
df_t['keyword'] = keyword_d.keys()
df_t['count'] = df_t['keyword'].apply(lambda x: keyword_d[x])
df_t.sort_values('count', ascending=False).to_csv('keyword_count.csv', index=False)
```

**Comment by rlskoeser** [comment]
No longer needed since we decided to pursue clustering based on tags.
