### ISSUE TITLE
Revise annotation model to link footnotes using foreign keys instead of URIs

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1238]
## Testing notes

On the QA admin site:

- [x] Check a few random transcriptions and confirm they are still present/accessible.
- [x] Check Log Entries for new footnotes added by the "script" user on Dec. 16, 2022, 2:16 pm. Click on some of the footnote objects: they should be "digital edition" footnotes with associated transcription content.
  - [x] Go to the document they belong to (PGPID/title should be in the "Content object" field) and confirm the digital edition for that author/source has transcription content (i.e. using Edit X's Edition, or the dropdown menu above the transcription text)
  - [x] On that document page, scroll down to the Footnotes section. Locate the digital edition footnote for the transcription you were just looking at, and check the "delete" box next to it at the far right end of the table. Click "save" at the bottom of the document page and confirm you get an error message, telling you that you can't delete a footnote with associated annotations here.

On the QA public site:

- [x] Check a few random transcriptions and confirm they are still visible on the public site; try editing them and confirm they show up in the editor too. (note: recent beta-tested editor fixes are not present on the site yet)

Please also test:

- #1207 
- #1280 

## dev notes

Epic to collect related or affected bugs/chores.

Initial steps: 

- [x] revise annotation model to add FK to footnote
- [x] data migration to associate existing footnotes + annotations explicitly
  - [x] if digital edition footnote cannot be found but source and document can, then create new digital edition (with LogEntry)
  - [x] generate report of any remaining problem annotations
- [x] if you delete a footnote from the document edit page, warn or prevent deletion
- [x] revise from json code to set footnote based on source + manifest uri when saving
- [x] revise to json code to serialize source & manifest uri when displaying
- [x] update annotation search methods
- [x] move signal handler footnote code into annotation view methods
- [x] everywhere we are looking up documents/sources by uri, we now get them by model accessors
- [ ] #1279
- Decided not to do this to avoid altering Tahqiq: ~remove `Document.from_manifest_uri`, `Document.id_from_manifest_uri`, `Source.from_uri`, and `Source.id_from_uri` and replace all usage with lookups on `Footnote`~

**Comment by blms** [comment]
Here is a list of known "digtial editions" without :

<details>
<summary>Digital editions without annotations</summary>

<ul>
<li>Digital Edition of Bodl. MS heb. c 28/6 (PGPID 547). Source: Jacob Mann, The Jews in Egypt and in Palestine under the Fâtịmid Caliphs (1970), vol. 2.
<li>Digital Edition of T-S 10J19.9 (PGPID 2944). Source: Moshe Gil, In the Kingdom of Ishmael‎ (in Hebrew) (1997), vol. 3.
<li>Digital Edition of T-S 8.168 + ENA 4011.54 (PGPID 3658). Source: S. D. Goitein, unpublished editions. (ENA)
<li>Digital Edition of T-S J2.66 (PGPID 6039). Source: A. L. Udovitch.
<li>Edition and Digital Edition of BL OR 5547.1 (PGPID 6235). Source: Yusuf Umrethwala, Athina Pfeiffer and Alan Elbaum, (in Arabic) (2022).
<li>Digital Edition of BL OR 5566B.1 (PGPID 6254). Source: Yusuf Umrethwala and Alan Elbaum, (in Arabic) (2022).
<li>Edition and Translation and Digital Edition of BL OR 5566B.19 (PGPID 6266). Source: Marina Rustow and Alan Elbaum, (in Arabic) (2022).
<li>Digital Edition of Bodl. MS heb. c 28/10 (PGPID 9545). Source: Alan Elbaum, (2022).
<li>Translation and Digital Edition of Bodl. MS heb. d 81/19–22 (PGPID 19470). Source: Marina Rustow, Alan Elbaum and Yusuf Umrethwala, (in Arabic) (2022).
<li>Digital Edition of T-S NS 137.29 (PGPID 23634). Source: Yusuf Umrethwala and Alan Elbaum, (in Arabic) (2022).
<li>Edition and Digital Edition of T-S NS 207.57 (PGPID 23940). Source: Yusuf Umrethwala and Alan Elbaum, (in Arabic) (2022).
<li>Edition and Digital Edition of AIU XII.80 (PGPID 29488). Source: Ṣabīḥ ʿAodeh, Eleventh Century Arabic Letters of Jewish Merchants from the Cairo Geniza‎ (in Hebrew) (1992).
<li>Digital Edition of AIU XII.84 (PGPID 30995). Source: Yusuf Umrethwala, Matthew Dudley and Alan Elbaum, (in Arabic).
<li>Digital Edition of Bodl. MS heb. b 11/7 (PGPID 31694). Source: Marina Rustow.
<li>Digital Edition of ENA 3700.1 (PGPID 32749). Source: Yusuf Umrethwala, (in Arabic) (2022).
<li>Digital Edition of NLI 577.1/75 (PGPID 33664). Source: Yusuf Umrethwala, (in Arabic) (2022).
<li>Digital Edition of JRL SERIES P 213 (PGPID 34440). Source: Alan Elbaum and Marina Rustow, Unpublished editions (2022).
<li>Edition and Digital Edition of BL OR 5557B.1 (PGPID 35188). Source: Marina Rustow, Alan Elbaum and Yusuf Umrethwala, (in Arabic) (2022).
<li>Digital Edition of ENA NS I.72 (PGPID 35825). Source: Yusuf Umrethwala and Alan Elbaum, (in Arabic) (2022).
<li>Digital Edition of ENA NS 13.15 (PGPID 36027). Source: Marina Rustow, Alan Elbaum and Yusuf Umrethwala, (in Arabic) (2022).
<li>Digital Edition of Bod. MS Heb. g 2/60–67 (PGPID 36479). Source: Yusuf Umrethwala, (in Arabic) (2022).
<li>Digital Edition of CUL Or. 1080 3.17 (PGPID 36489). Source: Marina Rustow, Alan Elbaum and Yusuf Umrethwala, (in Arabic) (2022).
<li>Digital Edition of BL OR 5557K.9 (PGPID 36498). Source: Yusuf Umrethwala and Alan Elbaum, (in Arabic) (2022).
<li>Digital Edition of BL Or. 5557K.11 (PGPID 36509). Source: Yusuf Umrethwala and Alan Elbaum, (in Arabic) (2022).
<li>Digital Edition of Moss. IXa,2.47 (PGPID 36528). Source: Yusuf Umrethwala and Alan Elbaum, (in Arabic) (2022).
</ul>

</details>

**Comment by kseniaryzhova** [comment]
@blms looks good, thank you! Closing!
