### ISSUE TITLE
Upgrade the python, Django, wagtail stack for Geniza 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#853]
## Testing notes (QA)

On the [test site](https://test-geniza.cdh.princeton.edu/), test the following categories to ensure that they still function as before.

In cases where things don't work as expected, check if they work the same way on the [production site](https://geniza.princeton.edu/) (except for destructive actions that would impact production data!). If they are also broken in production, file a new bug issue. If they are only broken in the test site, leave a comment here.

Note that production data was synced around 1:00pm ET on July 15, so any data changes made since then won't be reflected.

#### General
- [x] Use the light/dark switch
- [x] Use the language switch
- [x] Check all content pages (About, How To). The visual styles and content should match production
- [x] In the [Wagtail CMS](http://test-geniza.cdh.princeton.edu/cms), you should be able to add, edit, and delete content pages
- [x] Header and footer should appear as in production; links should work as expected

#### Search pages
- [x] general and regex searches on Documents
- [x] search results should show any: description, metadata, images, transcription/translation content
- [x] keyword search, filters, and sort on People
- [x] grid view/list view switcher on People
- [x] map and sort for Places
- [x] clicking on Place markers should scroll you to the place

#### Document detail pages
- [x] Navigate to a document page. Its look should match production, data should not be missing (including shelfmark, clickable tags list, "what's in the PGP")
- [x] image viewer: zoom, pan, rotate
- [x] navigate between multiple transcriptions and translations
- [x] open transcriptions and translations side by side and they should align
- [x] use the transcription editor; it should work as before (barring instances of the bug #1824)
- [x] Add a new transcription or translation and the Source autocomplete that appears should work
- [x] Select Bibliography tab
- [x] Related Documents tab

#### Person detail pages
- [x] Description, life events, citation, link, clickable social role, alternate names should all appear if present
- [x] Related People network graph; pan, zoom, click (when links appear), hover lines
- [x] Related Documents list/sorting
- [x] Related People list/sorting
- [x] Related places map
- [x] Related places list/sorting

#### Place detail pages
- [x] Map, coordinates, other name
- [x] Related documents list/sorting
- [x] Related people list/sorting

#### General
- [x] Filtering, searching, and sorting sections for Documents, Fragments, Sources, Footnotes
- [x] Merge tags in the Tags list (select w/ checkbox, then dropdown at the top)
- [x] Merge documents: data visible should match production site; merge should succeed
- [x] Merge Person-Document relationship types
- [x] Merge Person-Person relationship types
- [x] CSV exports for multiple/all documents
- [x] exports for multiple/all People
- [x] exports for multiple/all Places

#### Fragment edit page
- [x] Add IIIF URL (image) to a fragment—you can use the same URL as an existing one to test if you don't have a IIIF image handy (filter fragments by "has image")
- [x] Add related fragments

#### Document edit page
- [x] Add, edit, delete documents
- [x] View the edit history for a document, it should show edit history for some associated records too (matching production site)
- [x] Test autocompletes for primary language
- [x] Description in multiple languages
- [x] On a document that has images: use the rotation/order override
- [x] View transcriptions/translations from here
- [x] Autocomplete for tags; also try adding brand new tags, removing tags from document
- [x] Document date autoconversion (fill out "Date on document" + "Calendar", save, CE date should be filled in with the converted date. Ask Rachel if unsure)
- [x] Add inferred datings, fragments, related people/places/events, footnotes
- [x] Reorder fragments

#### Person edit page
- [x] relations CSV on individual Person edit page (top right)
- [x] Add, edit, delete people
- [x] for a new person, on save the slug should be autogenerated based on the primary name, with diacritics stripped
- [x] Multiple person roles
- [x] Active dates / deceased mention dates should match associated documents
- [x] Tags (add existing, create new, remove)

#### Place edit page
- [x] relations CSV on individual Place edit page (top right)
- [x] Add, edit, delete places
- [x] for a new place, on save the slug should be autogenerated based on the primary name, with diacritics stripped
- [x] Add coordinates to a place; on save its map should update to show the place

#### Event edit page
- [x] Add some dated documents to an event. The "Automatic date" on the event edit page should reflect the documents' dates

#### Footnote edit page
- [x] Source autocomplete dropdown
- [x] magnifying glass search icon by "object id" to choose a document
- [x] "document relation": selecting "Digital Edition" or "Digital Translation" should gray out all other options
- [x] Selecting the other options should gray out those two

#### Source edit page
- [x] Reorder authors for a multi-author source

---

## dev notes
determine which dependencies are blocking upgrade (if any still are) so we can keep an eye on them and update when possible

- [x] investigate what needs to be done in order to upgrade
- [x] Princeton-CDH/django-pucas#14
- [x] Princeton-CDH/djiffy#14
- [x] Princeton-CDH/parasolr#73
- [x] update to depend on new version of django-tabular-export 
- [x] replace `django.conf.urls.url()` with `django.urls.re_path()` in `urls.py`
- [x] bump django-taggit, taggit-selectize, django-modeltranslation, wagtail as below

**Comment by blms** [comment]
Findings from initial upgrades/testing:

- I successfully upgraded the following locally:
    ```
    django-taggit>=2.0,<3.0
    taggit-selectize>=2.11.0
    django-modeltranslation>=0.18.4
    wagtail>=2.16.2,<3.0
    ```
- The Wagtail upgrade requires a Taggit upgrade. Why was Taggit [pinned to <2.0](https://github.com/Princeton-CDH/geniza/commit/1e2c0e8fd1d060b37b0ff62b2619e727456007b2)? The only [breaking change](https://django-taggit.readthedocs.io/en/latest/changelog.html#id3) I could find looks like something we don’t use.
- pucas raises:
    ```py
    RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
        url(r'^login/$', LoginView.as_view(), name='cas_ng_login'),
    ```
- djiffy relies on an incompatible version of jsonfield:
    ```py
    File "/djiffy/models.py", line 20, in <module>
      from jsonfield import JSONField
    File "/jsonfield/__init__.py", line 1, in <module>
      from .fields import JSONCharField, JSONField  # noqa
    File "/jsonfield/fields.py", line 8, in <module>
      from django.utils.translation import ugettext_lazy as _
    ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/django/utils/translation/__init__.py)
    ```

- django-tabular-export makes a deprecated call. It doesn’t look like this project is maintained, do we need to fork it?
    ```py
    /tabular_export/core.py:93: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
   ```

- djiffy, pucas, parasolr all raise this warning, but it won’t come into play until Django 4.1, and FWIW django-multiselectfield and django-csp-helpers also raise it. But maybe worth flagging as 4.1 is currently in preview and will be released next month.
    ```py
    RemovedInDjango41Warning: 'djiffy' defines default_app_config = 'djiffy.apps.DjiffyConfig'. Django now detects this configuration automatically. You can remove default_app_config.
    app_config = AppConfig.create(entry)
    ```

Should I go ahead and make changes on djiffy, pucas, and parasolr? The JSONField one might be a little complicated but the rest look straightforward, so far.

**Comment by rlskoeser** [comment]
@blms thanks so much for reviewing and documenting! Don't worry about making the changes yet, I just wanted to have them identified so I know what is needed. I'll turn this into a checklist on this issue.

I don't remember why I pinned django-taggit, and boo on me for not documenting it.  I do remember wagtail localize causing problems, hopefully that has been resolved.

I can open a ticket on django-tabular-export — it's LoC folks, so I can ping them on twitter if need be. If it's not being maintained, maybe we need to switch to django-import-export (which I was thinking about looking at anyway for the import functionality).

Would it be worth creating an upgrade branch with the requirement changes you've made so far?

**Comment by blms** [comment]
@rlskoeser That all sounds good!

> Would it be worth creating an upgrade branch with the requirement changes you've made so far?

Probably not if we're not making the changes yet, my only change outside of the requirements I listed above was replacing `django.conf.urls.url()` with `django.urls.re_path()` in `urls.py`. So I think we can just put those two things in the checklist and do them when we're ready, in order to avoid potential merge conflicts, etc.

**Comment by blms** [comment]
> I don't remember why I pinned django-taggit, and boo on me for not documenting it.

FWIW, this is probably because Wagtail < 2.16 requires django-taggit < 2.0, so the two have to be upgraded simultaneously.

**Comment by kseniaryzhova** [comment]
@rlskoeser this is already done right? Confirm we can close?

**Comment by rlskoeser** [comment]
@kseniaryzhova no, I postponed it. Still important for maintenance and should be done at some point

**Comment by richmanrachel** [comment]
@rlskoeser or @blms -- Did this upgrade ever happen?

**Comment by blms** [comment]
@richmanrachel Not yet, but I believe @rlskoeser is working on the CDH parts of it.

**Comment by rlskoeser** [comment]
Sorry this has been stuck. We should be able to upgrade wagtail at least somewhat - I've done that on other projects, but we're limited on both until I get djiffy upgraded - on my list but a ways down. I'm making progress on some other maintenance so maybe I can fold this in too.

**Comment by rlskoeser** [comment]
@blms based on the commit it's probably a typo. Maybe you can test with a local checkout and editable install of djiffy and then one of you can propose and we can do a bugfix / micro release.

**Comment by mabdellatif88** [comment]
Update: I now have a healthy setup with wagtail 5.0, django 4.0, and python 3.10

**Comment by mabdellatif88** [comment]
Changes (so far) pushed to the branch upgrade_django

**Comment by amelbensalim** [comment]
Autocomplete for primary language is not immediately alphabetic -- typing "Ara" bring up the three kinds of Garshuni before "Arabic." 

<img width="625" height="359" alt="Image" src="https://github.com/user-attachments/assets/60fa2cfa-3df5-40fd-a2cf-5b01d9eadbc4" />

**Comment by amelbensalim** [comment]
The final two footnote edit page task on test admin site: 
"document relation": selecting "Digital Edition" or "Digital Translation" should gray out all other options

Selecting the other options should gray out those two

Neither of these seem to happen, either when editing an existing footnote or adding a new one
This is the final hurdle, otherwise this is finally ready to close! Thanks so much!
